// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wotspeudwmjopvxbehdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvdHNwZXVkd21qb3B2eGJlaGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjE1MjMsImV4cCI6MjA2MTkzNzUyM30.ewCNs6_ZAIJk6Q5RaWLqDFu3w4zR1SbpaLPA6tgztnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);